// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3bRa86R3Y4szi0rV_Ca6DQCop0XZRoTo',
    appId: '1:65916656556:web:cf42f57da2c7008a1a3809',
    messagingSenderId: '65916656556',
    projectId: 'findsport-fc9e0',
    authDomain: 'findsport-fc9e0.firebaseapp.com',
    storageBucket: 'findsport-fc9e0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzf3vRRkvrDzPsqeioiNcSs68Kl5rNTGs',
    appId: '1:65916656556:android:97d8b6bf08a732051a3809',
    messagingSenderId: '65916656556',
    projectId: 'findsport-fc9e0',
    storageBucket: 'findsport-fc9e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByu1BMT2NNfCKb8LGJVqzPjJSMhrk0AdU',
    appId: '1:65916656556:ios:5d5edff7a128bc8a1a3809',
    messagingSenderId: '65916656556',
    projectId: 'findsport-fc9e0',
    storageBucket: 'findsport-fc9e0.appspot.com',
    iosBundleId: 'com.example.localization1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByu1BMT2NNfCKb8LGJVqzPjJSMhrk0AdU',
    appId: '1:65916656556:ios:76ec656eeb5190551a3809',
    messagingSenderId: '65916656556',
    projectId: 'findsport-fc9e0',
    storageBucket: 'findsport-fc9e0.appspot.com',
    iosBundleId: 'com.example.localization1.RunnerTests',
  );
}
